apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshiksha-celery-worker.fullname" . }}
  labels:
    {{- include "openshiksha-celery-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celeryWorkerCount }}
  selector:
    matchLabels:
      {{- include "openshiksha-celery-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "openshiksha-celery-worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openshiksha.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-openshiksha
          image: alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: OPENSHIKSHA_HOST
              value: {{ include "openshiksha.fullname" . }}
            - name: OPENSHIKSHA_PORT
              value: {{ .Values.service.port | quote }}
          command:
            - /bin/sh
            - "-c"
          args:
            - "until /usr/bin/wget http://$OPENSHIKSHA_HOST:$OPENSHIKSHA_PORT; do echo \"waiting for openshiksha...\"; sleep 10; done"
      containers:
        - name: {{ include "openshiksha-celery-worker.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.tag }}"
          command: ["/usr/local/bin/celery"]
          args:
            - "-A"
            - "openshiksha"
            - "worker"
            - "-l"
            - "info"
          env:
            - name: OPENSHIKSHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openshiksha-secret
                  key: secret-key
            - name: OPENSHIKSHA_EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openshiksha-secret
                  key: email-host-password
            - name: OPENSHIKSHA_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openshiksha-secret
                  key: superuser-password
            - name: OPENSHIKSHA_SCHOOL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openshiksha-secret
                  key: school-admin-password
            - name: OPENSHIKSHA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: mysql-password
            - name: OPENSHIKSHA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: redis-password
            - name: OPENSHIKSHA_REDIS_HOST
              value: {{ .Release.Name }}-redis-master
            - name: OPENSHIKSHA_REDIS_PORT
              value: "6379"
            - name: OPENSHIKSHA_DB_HOST
              value: {{ .Release.Name }}-mysql
            - name: OPENSHIKSHA_DB_PORT
              value: "3306"
            - name: OPENSHIKSHA_CABINET_HOST
              value: {{ include "openshiksha.fullname" . }}
            - name: OPENSHIKSHA_ENV
              value: {{ .Values.tag | upper | quote }}
            - name: OPENSHIKSHA_CABINET_PORT
              value: {{ .Values.service.port | quote }}
            - name: OPENSHIKSHA_SALES_PHONE
              value: {{ .Values.env.salesPhone | quote }}
            - name: OPENSHIKSHA_CONTACT_PHONE
              value: {{ .Values.env.contactPhone | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "celery inspect ping -A openshiksha -d celery@$HOSTNAME"
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "celery inspect ping -A openshiksha -d celery@$HOSTNAME"
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
