apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshiksha.fullname" . }}
  labels:
    {{- include "openshiksha.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openshiksha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "openshiksha.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openshiksha.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-mysql
          image: alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOST
              value: {{ .Release.Name }}-mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: openshiksha_app
            - name: MYSQL_DATABASE
              value: openshiksha
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: mysql-password
          command:
            - /bin/sh
            - "-c"
          args:
            - "apk add mysql-client && until /usr/bin/mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -D $MYSQL_DATABASE -p$MYSQL_PASSWORD -e \"show tables\"; do echo \"waiting for mysql...\"; sleep 10; done"
      containers:
        - name: {{ include "openshiksha.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.tag }}"
          env:
            - name: OPENSHIKSHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openshiksha-secret
                  key: secret-key
            - name: OPENSHIKSHA_EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openshiksha-secret
                  key: email-host-password
            - name: OPENSHIKSHA_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openshiksha-secret
                  key: superuser-password
            - name: OPENSHIKSHA_SCHOOL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openshiksha-secret
                  key: school-admin-password
            - name: OPENSHIKSHA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: mysql-password
            - name: OPENSHIKSHA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: redis-password
            - name: OPENSHIKSHA_REDIS_HOST
              value: {{ .Release.Name }}-redis-master
            - name: OPENSHIKSHA_REDIS_PORT
              value: "6379"
            - name: OPENSHIKSHA_DB_HOST
              value: {{ .Release.Name }}-mysql
            - name: OPENSHIKSHA_DB_PORT
              value: "3306"
            - name: OPENSHIKSHA_CABINET_HOST
              value: {{ include "openshiksha.fullname" . }}
            - name: OPENSHIKSHA_ENV
              value: {{ .Values.tag | upper | quote }}
            - name: OPENSHIKSHA_CABINET_PORT
              value: {{ .Values.service.port | quote }}
            - name: OPENSHIKSHA_SALES_PHONE
              value: {{ .Values.env.salesPhone | quote }}
            - name: OPENSHIKSHA_CONTACT_PHONE
              value: {{ .Values.env.contactPhone | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
